name = "gospel-lyrics-platform"
compatibility_date = "2024-01-01"
pages_build_output_dir = "src"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "gospel-lyrics-db"
database_id = "7d29f542-135f-42cf-bc65-626b097b68ed"

[vars]
DOMAIN = "gospellyricsub.com"
PESAPAL_BASE = "https://pay.pesapal.com/v3/api"
PESAPAL_CALLBACK_URL = "https://gospellyricsub.com/pay/callback"
