name = "gospel-lyrics-platform"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "gospel-lyrics-db"
database_id = "replace-with-actual-db-id"

[vars]
DOMAIN = "gospellyricsub.com"
PESAPAL_BASE = "https://pay.pesapal.com/v3/api"
PESAPAL_CALLBACK_URL = "https://gospellyricsub.com/pay/callback"
